/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_huanqi_myapplication_DataProvider */

#ifndef _Included_com_example_huanqi_myapplication_DataProvider
#define _Included_com_example_huanqi_myapplication_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_huanqi_myapplication_DataProvider
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_huanqi_myapplication_DataProvider_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_huanqi_myapplication_DataProvider
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_huanqi_myapplication_DataProvider_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
